# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='photo',
            field=models.ImageField(upload_to='static\\posters'),
        ),
    ]
