# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_auto_20170912_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='photo',
            field=models.ImageField(upload_to='posters'),
        ),
    ]
