# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_auto_20170912_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='photo',
            new_name='poster',
        ),
    ]
