# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 04:27
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0004_auto_20170924_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='poster',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
